name: Build Tauri App for ARM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri App
        run: |
          cd src-tauri
          cross build --release --target ${{ matrix.target }}
