name: Build Tauri App for ARM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          if [ "${{ matrix.target }}" = "armv7-unknown-linux-gnueabihf" ]; then
            sudo apt-get install -y gcc-arm-linux-gnueabihf
          elif [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi

      - name: Build Tauri App
        run: |
          cd src-tauri
          cargo build --release --target ${{ matrix.target }}
